#!/bin/bash

# Get the target remote information
REMOTE=$@

# Check sockets folder exists
if [ ! -d $HOME/.ssh/sockets ]; then
    mkdir -p $HOME/.ssh/sockets
fi

# Generate unique id for socket name
UNIQUE_ID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

# Initiate master connection
SSHSOCKET=$HOME/.ssh/sockets/shally-$UNIQUE_ID.sock
ssh -M -f -N -o ControlPath=$SSHSOCKET $REMOTE

# Pre command hook
ssh -o ControlPath=$SSHSOCKET $REMOTE "touch /tmp/$UNIQUE_ID.txt"

# Call the actual command
ssh -o ControlPath=$SSHSOCKET $REMOTE

# Post command hook
ssh -o ControlPath=$SSHSOCKET $REMOTE "rm -f /tmp/$UNIQUE_ID.txt"

# Close the master connection
ssh -S $SSHSOCKET -O exit $REMOTE
